class CommSec:
    HOME_URL = 'https://www2.commsec.com.au/'
    SECURITY_PARTIAL_URL = 'https://www2.commsec.com.au/quotes/summary?stockCode=___&exchangeCode=ASX'
    CLIENT_ID = '//input[@id="ctl00_cpContent_txtLogin"]'
    PASSWORD = '//input[@id="ctl00_cpContent_txtPassword"]'
    ACCOUNT_DETAILS = '//span[@id="ctl00_BodyPlaceHolder_HomePrivateView1_settlementWidget_ddAccountList_lblAccount_field"]'
    INSTRUMENT_DETAILS = '//h1[@class="instrument-details__stock"]'
    EXCHANGE_CODE = '//span[@id="overview-exchange-code"]'
    SECURITY_CODE = '//span[@id="overview-security-code"]'
    LAST_PRICE = '//span[@class="stock-price__last-price-value"]'
    TODAYS_CHANGE_AMOUNT = '//span[@class="stock-price__todays-change-amount"]'
    STOCK_DETAILS_ITEM = '//li[@class="stock-details__item"]'
    STOCK_DETAILS_ITEM_SINGLE_FIELD ='//li[@class="stock-details__item ng-star-inserted"]'
    ORDER_BOOK = '//tr[@class="qr-table__row ng-star-inserted"]'
    REFRESH = '//button[@class="button button--clean header-button"]'